config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions do
    get :apply_category_to_similar, on: :member
    get :run_rules, on: :collection
    get :import, on: :collection
  end

  root to: 'visitors#index'
  devise_for :users
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  serialize :tags

  scope :order_latest, ->{ order(date: :desc, created_at: :asc) }
  scope :expenses, ->{ where(transaction_type:'expense') }
  scope :incomes, ->{ where(transaction_type:'income') }
  scope :similar, ->(description_id){ where(description_id: description_id) }

  scope :for_month, ->(date_str){
    d = Date.parse(date_str)
    where(date: [d.beginning_of_month..d.end_of_month])
  }

  scope :for_category, ->(category){
    if category == 'none'
      where(category: nil)
    else
      where(category: category)
    end

  }

  scope :spending_expenses, ->{ expenses.where("category <> ?", 'internal transfer') }

  before_save :update_description_id, :run_rules

  CATEGORIES = [
    'utilities/telecomms',
    'computer hardware',
    'entertainment/events/culture',
    'haircut',
    'fix/replace',
    'trip trasnport',
    'gift',
    'public transport',
    'house stuff',
    'education',
    'fitness/gym/yoga',
    'food and drink',
    'life admin',
    'trip money',
    'doctors/medicine/health',
    'btmetrics',
    'taxi',
    'shopping',
    'groceries',
    'rent',
    'internal transfer',
    'current account transfer',
    'tax',
    'company admin',
    'parking',
    'car insurance',
    'car',
    '** suspicious/unknown',
    'cash'
  ]

  def self.filter(params)
    query = order_latest

    if params[:month].present?
      query = query.for_month(params[:month])
    end

    if params[:transaction_type].present?
      query = query.where(transaction_type: params[:transaction_type])
    end

    if params[:category].present?
      query = query.for_category params[:category]
    end

    query
  end

  def self.import(format, uri)
    "Importers::#{format.to_s.titleize}Importer".constantize.new(uri).import
  end

  def self.for_tag(tag)

    if tag
      where("tags like ?", "%#{tag}%")
    else
      where('true = true')
    end

  end

  def self.run_rules
    Transaction
      .where(category: nil)
      .find_each(batch_size: 500) do |t|
        t.run_rules
        t.save!
      end
  end

  def find_similar_to_me_with_trigger
    similar_to_me
      .where("triggered_apply_to_similar is not null")
      .first
  end

  def similar_to_me
    Transaction.similar(description_id).where('id <> ?', self.id || 0)
  end

  def apply_category_to_similar!

    if description.present? && description_id.present?

      Transaction.transaction do
        similar_to_me
          .where("category is null OR category = ''")
          .update_all category: category, triggered_apply_to_similar: Date.today

        self.update_attributes! triggered_apply_to_similar: Date.today
      end

    end

  end

  def has_dupe?
    query = Transaction.where(date: date, transaction_type: transaction_type, description: description).where.not(id: id)

    if !amount && amount_non_gbp > 0
      query = query.where(amount_non_gbp: amount_non_gbp)
    else
      query = query.where(amount: amount)
    end

    query.first
  end

  def update_description_id
    self.description_id = description.urlify
  end

  def run_rules
    RulesRunner.new(self).call
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: "andy", password: "viocorp11"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :load_transaction, only: [:update, :apply_category_to_similar]

  def index

    respond_to do |format|
      format.html
      format.json { 
        pre_category_transactions = Transaction.filter(params.except(:category))
        @categories = (pre_category_transactions
          .pluck(:category)
          .uniq.to_a
          .select(&:present?) + ['none'])
          .map do |category|
            {
              name: category,
              amount: pre_category_transactions.for_category(category).pluck(:amount).sum
            }
          end
        @transactions = Transaction.filter(params)
      }
    end

  end

  def apply_category_to_similar
    @transaction.apply_category_to_similar!
    @transactions = Transaction.filter(params)
    render json: {success: true}
  end

  def run_rules
    Transaction.run_rules
    @transactions = Transaction.filter(params)
    render json: {success: true}
  end

  def update
    @transaction.update_attributes! strong_params
    render json: {success: true}
  end

  def import
    if params[:uri].present?
      Transaction.import params[:bank], params[:uri]
      redirect_to root_path
    end
  end

  private

  def load_transaction
    @transaction = Transaction.find params[:id]
  end

  def strong_params
    params.require(:transaction).permit :category
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    if Transaction.any?
      @start_date = (params[:start_date] && Date.parse(params[:start_date])) || Transaction.order(date: :asc).first.date.beginning_of_month 
      @end_date = params[:end_date] && Date.parse(params[:end_date]) || (Time.now - 1.month).beginning_of_month.to_date

      transactions = Transaction.spending_expenses.where(date: [@start_date..@end_date])

      @calculator = SpendCalculator.new(transactions)
    else
      redirect_to import_transactions_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Budge', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li = link_to 'Import data', import_transactions_path
        li = link_to 'Transactions', transactions_path(month: Date.today.beginning_of_month)
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Budge'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Budge'}"
    == stylesheet_link_tag "application", :media => 'all'
    
    - if content_for?(:main_js_file)
      == yield(:main_js_file)
    - else
      == javascript_include_tag 'application'

    
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/transactions/_transaction_row.html.slim
tr class='transaction-row-#{t.id}'
  td = t.date.strftime("%a, %d %b, %Y")
  td = number_to_currency(t.amount)
  td
    .description-container
      | #{t.description} |
      a href='#' data-toggle=".js-raw-description-container-#{t.id}" show raw
    div class="js-raw-description-container-#{t.id}" style='display: none;'
      small #{t.original_date} | #{t.raw_description}
  td: a href='#' data-toggle="#edit_transaction_#{t.id}": span.label.label-default = t.category
  td
    = form_for t, remote: true, html: {class: "form-inline", style: "#{'display: none;' if t.category.present?}"} do |f|
      = hidden_field_tag :month, params[:month]
      = hidden_field_tag :transaction_type, params[:transaction_type]
      = hidden_field_tag :category, params[:category]

      .form-group
        = f.select :category, options_for_select(Transaction::CATEGORIES.sort.uniq), {prompt: 'select a category'}, class: 'form-control select-category'
      = f.submit 'add category', class: 'btn btn-primary hide', data:{ disable_with: 'saving category' }
  td
    - if t.category.present? && !t.triggered_apply_to_similar
      = link_to 'Apply to similar', apply_category_to_similar_transaction_path(t, month: params[:month], transaction_type: params[:transaction_type], category: params[:category]), data: { no_turbolink: true }, remote: true, class: 'btn btn-primary'
  td: input.quick-sum-checkbox type="checkbox" value="#{t.amount}"

app/views/transactions/apply_category_to_similar.js.erb
$('table tbody').html('<%= j render 'transaction_rows' %>');

app/views/transactions/import.html.slim
= form_tag(import_transactions_path, method: :get) do
  .form-group
    = text_field_tag :uri, params[:uri], class: 'form-control' 
    = select_tag :bank, options_for_select([ "barclays", "lloyds", "revolut", "sabadell" ], "barclays")
    = submit_tag :import, class: 'btn btn-lg btn-default'

app/views/transactions/index.html.slim
- content_for(:main_js_file) do
  == javascript_pack_tag 'application'

app/views/transactions/update.js.erb
$('.transaction-row-<%= @transaction.id%>').replaceWith('<%= j render 'transaction_row', t: @transaction %>');